version: '3.8'
services:
  app:
    container_name: my-currency-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true